module CallPoints {
  import csharp

  // This xml part is commonly seen in Microsoft framework auto generated files
  // Other frameworks probably use different indicators.
  class AutoGeneratedFile extends File {
    AutoGeneratedFile() {
      exists(CommentLine comment | comment.getLocation().getFile() = this |
        comment.getText().indexOf("<auto-generated") != -1
      )
    }
  }

  class InboundCallPoint extends Callable {
    InboundCallPoint() {
      not this.getFile() instanceof AutoGeneratedFile and
      this.fromSource() and
      not exists(Callable caller | caller.calls(this)) and
      // Calls without caller are possible in field and property initialization
      not exists(Call call | call.getTarget() = this) and
      not exists(Callable declarationScope | this.getEnclosingCallable() = declarationScope) and
      not this.getDeclaringType() instanceof Interface and
      (this instanceof Method or this instanceof AnonymousFunctionExpr) and
      this.hasNonEmptyBody() and
      not exists(Method m | m = this | m.isEffectivelyPrivate()) and
      not exists(Method m | m = this | m.isExtensionMethod())
    }
  }

  class OutboundCallPoint extends Callable {
    OutboundCallPoint() { fromLibrary() }
  }
}
